# Generated by Django 5.0.3 on 2024-03-10 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MessageBoard', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='MessageBoard',
        ),
    ]
